server:
  port: 7979
spring:
  application:
    name: turbine
  cloud:
    consul:
      host: consul
      port: 8500
turbine:
  aggregator:
    clusterConfig: hystrix
  appConfig: hystrix
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream