version: '2.2'
services:
  consul:
    image: consul:latest
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
  hystrix:
    build:
      context: "hystrix"
      dockerfile: ./docker/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - consul
    links:
      - consul:consul
  turbine:
    build:
      context: "turbine"
      dockerfile: ./docker/Dockerfile
    ports:
      - "7979:7979"
    depends_on:
      - consul
    links:
      - consul:consul
  dashboard:
    build:
      context: "dashboard"
      dockerfile: ./docker/Dockerfile
    ports:
      - "8090:8090"
    depends_on:
      - consul
    links:
      - consul:consul
    

